<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdownBday</name>
   <tag></tag>
   <elementGuidId>dfc95370-9e56-4457-bad9-7b0ffcb69da5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class='abv-dateSelect']/*[@id='bDay']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class='abv-dateSelect']/*[@id='bDay']</value>
   </webElementProperties>
</WebElementEntity>
