<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdownByear</name>
   <tag></tag>
   <elementGuidId>fd6c0bd3-22ec-4c2e-8035-11ac8875eb2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class='abv-dateSelect']/*[@id='bYear']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class='abv-dateSelect']/*[@id='bYear']</value>
   </webElementProperties>
</WebElementEntity>
