<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>receiveEmailSubject</name>
   <tag></tag>
   <elementGuidId>c4fa78ad-b62b-478a-bae2-cb28c13406fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class='abv-MessageContainer']//*[@class='abv-letterSubject']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class='abv-MessageContainer']//*[@class='abv-letterSubject']</value>
   </webElementProperties>
</WebElementEntity>
