<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sendEmailButton</name>
   <tag></tag>
   <elementGuidId>365c9412-a856-4ef0-a9cf-eb4d1b26c596</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class='sendMenuContent']/*[@class='abv-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class='sendMenuContent']/*[@class='abv-button']</value>
   </webElementProperties>
</WebElementEntity>
