<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>writeAnEmailButton</name>
   <tag></tag>
   <elementGuidId>a90f208c-ba4e-4e13-8098-27818ccb2254</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class='abv-button']/text()[normalize-space(.)='Напиши']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class='abv-button']/text()[normalize-space(.)='Напиши']</value>
   </webElementProperties>
</WebElementEntity>
